### model
trust_remote_code: true


### method
stage: sft
do_train: true
deepspeed: examples/deepspeed/ds_z3_config.json  

### dataset
template: llama3
cutoff_len: 2048
max_samples: 3000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4

### output
logging_steps: 10
save_steps: 3000
plot_loss: true
save_only_model: true
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 16
gradient_accumulation_steps: 4
learning_rate: 0.0001
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
compute_accuracy: True
## eval
# # val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
model_name_or_path: /media/volume/V3/Llama-3.2-1B-Instruct
adapter_name_or_path: /media/volume/V3/stm_experiment/20251212_213528_mask/lora_base/aqua_cot
finetuning_type: lora
lora_rank: 16
lora_alpha: 16
lora_dropout: 0.05
lora_target: all
dataset: openbookqa
output_dir: /media/volume/V3/stm_experiment/20251212_213528_mask/lora_transfer/aqua_cot_to_openbookqa